### ISSUE TITLE
CDbException when add is prevented by onBeforeMultiAddToCart

### ISSUE THREAD

**Issue by Tam** [engram-design/MultiAdd#8] opened 2016-09-22 10:20 UTC
If I set `$event->performAction = false;` in the `onBeforeMultiAddToCart` event, I get the following error:

```
CDbException

CDbTransaction is inactive and cannot perform commit or roll back operations. (/.../craft/app/framework/db/CDbTransaction.php:84)

#0  /.../craft/plugins/commerce/Commerce/Helpers/CommerceDbHelper.php(54): CDbTransaction->rollback()
#1  /.../craft/plugins/multiadd/services/MultiAdd_CartService.php(189): Commerce\Helpers\CommerceDbHelper::rollbackStackedTransaction()
#2  /.../craft/plugins/multiadd/controllers/MultiAddController.php(64): Craft\MultiAdd_CartService->multiAddToCart(Object(Craft\Commerce_OrderModel), Array, '')
#3  /.../craft/app/framework/web/actions/CInlineAction.php(49): Craft\MultiAddController->actionMultiAdd()
#4  /.../craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5  /.../craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6  /.../craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7  /.../craft/app/framework/web/CWebApplication.php(282): CController->run('multiAdd')
#8  /.../craft/app/etc/web/WebApp.php(818): CWebApplication->runController('multiAdd/multiA...')
#9  /.../craft/app/etc/web/WebApp.php(288): Craft\WebApp->_processActionRequest()
#10 /.../craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#11 /.../craft/app/index.php(62): CApplication->run()
#12 /.../public/index.php(19): require_once('/...')
#13 {main}
```

**Comment by bossanova808** [comment] 2016-09-22 10:36
@tam - that's a bit odd.  The event stuff is cribbed directly from the standard addToCart controller and it basically just rolls back the transaction it started if performAction is false (https://github.com/engram-design/MultiAdd/blob/master/multiadd/services/MultiAdd_CartService.php#L132) 

Can't immediately see anything wrong with that to be honest.  I might have to ask Luke for a hint on this...unless @engram-design you have any ideas?

**Comment by engram-design** [comment] 2016-09-22 13:45
I'll have to do some testing on this one, but not something I've come across yet with MultiAdd...

**Comment by engram-design** [comment] 2016-09-25 12:22
@bossanova808 I believe I came across a similar issue when Commerce first started, which is the reason for the whole `CommerceDbHelper` stuff. I'll investigate a bit more...

**Comment by bossanova808** [comment] 2016-09-25 23:47
I'm all good with this and the cleanup work in general is a good idea...only thing is by moving from exceptions etc, it will mean multiadd behaves differently (but better!) to Commerce itself...when I knocked it up I was very much trying to keep it as close to Commerce as possible in behaviour.  But I am all for better error messages so thumbs up from me!

I had a busy weekend and a busy week coming up so will leave this in your hands!!  Thanks Josh!

**Comment by engram-design** [comment] 2016-09-26 00:11
@bossanova808 Yeah, totally understand trying to keep it the same as native Commerce! The `CommerceDbHelper` stuff is something a little trickier I recon.

**Comment by bossanova808** [comment] 2017-06-14 00:33
Given `CommerceDbHelper` is no longer used by Commerce or multiadd, I think I will close this one.  Someone will re-open if there is still an issue anywhere!

**Closed as completed by bossanova808** 2017-06-14 00:33 UTC

**Comment by engram-design** [comment] 2019-01-31 22:59
Just for future reference, I'd say this can also be caused by another plugin throwing an error before reaching this part of code. Not sure why, but an error thrown in another plugin seems to cause issues by resetting the transaction or something.

Commenting out the `$transaction->rollback();` in `Commerce_CartService.php` helped to uncover this. FYI, this in particular wasn't a Multi Add issue, but an issue with our Events plugin and Instant Analytics throwing an error, but this same error popped up.
